# Generated by Django 4.2.5 on 2023-10-01 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_remove_product_owner_product_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonview',
            name='last_viewed_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
