# Generated by Django 4.2.5 on 2023-10-01 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_lessonview_last_viewed_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_views', models.IntegerField(default=0)),
                ('total_time_spent', models.IntegerField(default=0)),
                ('total_students', models.IntegerField(default=0)),
                ('purchase_percentage', models.FloatField(default=0.0)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='index.product')),
            ],
        ),
    ]
