# Generated by Django 4.2.5 on 2023-10-01 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_productstatistics'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductStatistics',
        ),
    ]
